version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todos
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
