version: '3.8'
services:
  db:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./app/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
volumes:
  db_data:
